(() => {
'use strict';
const D=window.BIBLIOGRAPHY,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=Object.fromEntries(D.cases.map(c=>[c.id,c])),terms=Object.fromEntries(D.terms.map(t=>[t.id,t]));
const caseTitle=c=>c.title.replace(/^\d+[.,]\s*/,'');
const labels={name:'Case study name',type:'Type',description:'Description',institution:'Institution',place:'Place / Context',time_frame:'Time frame',participants:'Participants',evaluator_role:'Evaluator role',data_type:'Data type',data_source:'Evidence collected',complexity:'Complexity',year:'Year',citation:'Bibliographic reference',stage:'Evaluation stage',aim:'Evaluation aim',methods:'Methods & tools',practices:'Design practices'};
const defaults=['practices','methods','data_source'];
const state={selected:null,hovered:null,tab:'overview',view:'network',evidence:null,visible:[],edges:[],zoom:1,panX:0,panY:0};
let layoutCache={key:null,positions:null},previewTimer;
const manualPositions=new Map();
const focusPositions=new Map();
let displayPositions={},layoutFrame=0,savedViewport=null;
let drag=null,suppressClickUntil=0;
const searchIndex=Object.fromEntries(D.cases.map(c=>[c.id,[...Object.values(c.fields).flat().map(e=>e.value),...c.stages.flatMap(s=>Object.values(s.fields).map(e=>e.value))].join(' ').toLowerCase()]));
$('#dimensions').innerHTML=D.dimensions.map(d=>`<label class="dimension"><input type="checkbox" name="dimension" value="${d.id}" ${defaults.includes(d.id)?'checked':''}><span>${escape(labels[d.id])}</span></label>`).join('');
const guideNotes={practices:'Find cases that share design practices, such as cultural probes or reflective practice.',methods:'Compare the tools and methods used to carry out an evaluation.',data_source:'Explore cases that collect similar evidence, such as interviews, observations, or participant feedback.',stage:'Explore shared steps in the evaluation process.',institution:'Find cases associated with the same institution.',data_type:'Explore qualitative, quantitative, and mixed approaches. This broad characteristic connects many cases.',type:'Explore cases described as the same type of evaluation or activity.'};
$('#profiles').innerHTML=D.dimensions.map(d=>`<article class="profile"><h4>${escape(labels[d.id])} ${defaults.includes(d.id)?'<span class="badge">Starting point</span>':''}</h4><p>${guideNotes[d.id]}</p><div class="metrics"><span>${d.pairs} connections</span><span>${d.cross_category_pairs} across collections</span></div></article>`).join('');
function selectedDimensions(){return $$('input[name=dimension]:checked').map(x=>x.value)}
function updateTerms(){const dims=selectedDimensions(),old=$('#term').value;$('#term').innerHTML='<option value="">All values</option>'+D.terms.filter(t=>dims.includes(t.dimension)&&t.case_ids.length>1).sort((a,b)=>b.case_ids.length-a.case_ids.length||a.label.localeCompare(b.label)).map(t=>`<option value="${escape(t.id)}">${escape(t.label)} · ${t.case_ids.length} cases (${escape(labels[t.dimension])})</option>`).join('');if([...$('#term').options].some(o=>o.value===old))$('#term').value=old;}
function render(){hidePreview();const cats=$$('input[name=category]:checked').map(x=>x.value),q=$('#search').value.trim().toLowerCase(),term=$('#term').value,dims=selectedDimensions();
state.visible=D.cases.filter(c=>cats.includes(c.category)&&(!q||searchIndex[c.id].includes(q))&&(!term||Object.values(c.dimensions).flat().includes(term)));
const ids=new Set(state.visible.map(c=>c.id));state.edges=D.edges.filter(e=>ids.has(e.source)&&ids.has(e.target)).map(e=>({...e,shared:Object.fromEntries(Object.entries(e.shared).filter(([d,ts])=>dims.includes(d)&&(!term||ts.includes(term))))})).filter(e=>Object.keys(e.shared).length>0);
if(state.selected&&!ids.has(state.selected)){state.selected=null;state.evidence=null;restoreViewport();}focusPositions.clear();
$('#result-count').textContent=`${state.visible.length} / 32 cases`;
const connected=new Set(state.edges.flatMap(e=>[e.source,e.target]));
$('#map-summary').textContent=`${state.edges.length} connections · ${state.visible.length-connected.size} unconnected cases`;
$('#dimension-summary').textContent=dims.length?dims.map(d=>labels[d]).join(' · '):'Choose a characteristic to reveal connections';
$('#empty').hidden=state.visible.length>0;
$('#library').innerHTML=state.visible.length?state.visible.map(c=>`<button class="library-item" data-case="${c.id}"><small><i class="dot ${c.id[0]==='C'?'creative':'participatory'}"></i> ${escape(c.category)}</small><h3>${escape(caseTitle(c))}</h3><p>${escape(c.description||'Description not available.')}</p><small>${c.stages.length?c.stages.length+' evaluation stages':'Evaluation stages not listed'}</small></button>`).join(''):'<p class="source-text">No cases match these filters.</p>';
renderGraph();renderInspector();
}
function graphLayout(){const cacheKey=state.visible.map(c=>c.id).join(',')+'|'+state.edges.map(e=>e.source+e.target).join(',');if(layoutCache.key===cacheKey)return layoutCache.positions;const n=state.visible.length,positions=state.visible.map((c,i)=>({id:c.id,x:450+Math.cos(i*2.39996)*Math.sqrt((i+1)/(n||1))*300,y:350+Math.sin(i*2.39996)*Math.sqrt((i+1)/(n||1))*230})),map=Object.fromEntries(positions.map(p=>[p.id,p]));
for(let iter=0;iter<250;iter++){const cool=1-iter/280,forces=Object.fromEntries(positions.map(p=>[p.id,{x:(450-p.x)*.006,y:(350-p.y)*.006}]));for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){const a=positions[i],b=positions[j],dx=a.x-b.x,dy=a.y-b.y,dist=Math.max(Math.hypot(dx,dy),1),rep=15000/(dist*dist);forces[a.id].x+=dx/dist*rep;forces[a.id].y+=dy/dist*rep;forces[b.id].x-=dx/dist*rep;forces[b.id].y-=dy/dist*rep}for(const e of state.edges){const a=map[e.source],b=map[e.target],dx=b.x-a.x,dy=b.y-a.y,dist=Math.max(Math.hypot(dx,dy),1),f=(dist-108)*.015;forces[a.id].x+=dx/dist*f;forces[a.id].y+=dy/dist*f;forces[b.id].x-=dx/dist*f;forces[b.id].y-=dy/dist*f}for(const p of positions){p.x=Math.max(75,Math.min(825,p.x+Math.max(-8,Math.min(8,forces[p.id].x))*cool));p.y=Math.max(110,Math.min(590,p.y+Math.max(-8,Math.min(8,forces[p.id].y))*cool));}}
for(const [id,p] of manualPositions){if(map[id])Object.assign(map[id],p)}
layoutCache={key:cacheKey,positions:map};return map;}
function restoreViewport(){focusPositions.clear();if(savedViewport){Object.assign(state,savedViewport);savedViewport=null;}}
// Focus is a temporary presentation of direct links, independent of the saved free layout.
function focusedLayout(base){const pos=Object.fromEntries(Object.entries(base).map(([id,p])=>[id,{...p}]));if(!state.selected||!pos[state.selected])return pos;
const neighbors=new Set(state.edges.filter(e=>e.source===state.selected||e.target===state.selected).flatMap(e=>[e.source,e.target]));neighbors.delete(state.selected);
const ordered=ids=>ids.sort((a,b)=>Math.atan2(base[a].y-350,base[a].x-450)-Math.atan2(base[b].y-350,base[b].x-450));
pos[state.selected]={id:state.selected,x:450,y:350};
const connected=ordered([...neighbors]),outer=ordered(Object.keys(pos).filter(id=>id!==state.selected&&!neighbors.has(id)));
const ring=(ids,rx,ry)=>ids.forEach((id,i)=>{const angle=-Math.PI/2+i*2*Math.PI/ids.length;pos[id]={id,x:450+Math.cos(angle)*rx,y:350+Math.sin(angle)*ry}});
if(connected.length<=10)ring(connected,145,145);else{ring(connected.slice(0,8),115,115);ring(connected.slice(8),220,220)}
ring(outer,355,270);for(const [id,p] of focusPositions)if(pos[id])Object.assign(pos[id],p);return pos;}
function paintPositions(){for(const node of $$('#network .node')){const p=displayPositions[node.dataset.case];node.setAttribute('transform',`translate(${p.x},${p.y})`)}for(const line of $$('#network .edge')){const a=displayPositions[line.dataset.source],b=displayPositions[line.dataset.target];line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y)}}
function renderGraph(animate=false){cancelAnimationFrame(layoutFrame);layoutFrame=0;const previous=displayPositions,pos=focusedLayout(graphLayout());displayPositions=pos;
const used=[],placed={};
const overlaps=(a,b)=>a.x<b.x+b.w+7&&a.x+a.w+7>b.x&&a.y<b.y+b.h+5&&a.y+a.h+5>b.y;
for(const c of state.visible){const p=pos[c.id],title=c.title.replace(/^\d+[.,]\s*/,''),short=title.length>23?title.slice(0,21)+'…':title;let found;
for(const label of [short,title.length>12?title.slice(0,10)+'…':title]){const w=label.length*9.3,h=20;for(const [dx,dy] of [[0,34],[0,-24],[w/2+22,6],[-w/2-22,6],[0,54],[0,-44]]){const x=Math.max(w/2+8,Math.min(892-w/2,p.x+dx)),box={x:x-w/2,y:p.y+dy-h,w,h};if(used.some(b=>overlaps(box,b))||Object.values(pos).some(n=>n.id!==c.id&&overlaps(box,{x:n.x-15,y:n.y-15,w:30,h:30})))continue;found={label,x:x-p.x,y:dy};used.push(box);break}if(found)break}placed[c.id]=found||{label:'',x:0,y:34};}
const edgeHtml=state.edges.map(e=>`<line class="edge" data-source="${e.source}" data-target="${e.target}" x1="${pos[e.source].x}" y1="${pos[e.source].y}" x2="${pos[e.target].x}" y2="${pos[e.target].y}" stroke-width="${1+Object.keys(e.shared).length*.4}"/>`).join('');
const nodes=state.visible.map(c=>{const p=pos[c.id],degree=state.edges.filter(e=>e.source===c.id||e.target===c.id).length,r=12+Math.min(degree,9)*.65,l=placed[c.id];return `<g class="node" role="button" tabindex="0" data-case="${c.id}" aria-label="${escape(caseTitle(c))}; ${degree} connections" aria-description="Drag to move. Arrow keys move a focused node; Enter opens the case." aria-keyshortcuts="ArrowUp ArrowDown ArrowLeft ArrowRight" aria-pressed="false" transform="translate(${p.x},${p.y})"><circle class="node-hit" r="26" fill="transparent"/><circle class="node-halo" r="${r+6}" fill="${c.id[0]==='C'?'#7160d8':'#118c85'}"/><circle class="node-core" r="${r}" fill="${c.id[0]==='C'?'#8071df':'#26a397'}"/><text text-anchor="middle" x="${l.x}" y="${l.y}">${escape(l.label)}</text></g>`}).join('');
$('#network').innerHTML=`<g id="map-layer">${state.selected?'<circle class="focus-region" cx="450" cy="350" r="245"/>':''}${edgeHtml}${nodes}</g>`;transform();updateHighlights();
const degree=state.edges.filter(e=>e.source===state.selected||e.target===state.selected).length;
$('#focus-note').hidden=!state.selected;$('#focus-note').textContent=degree?`${degree} connected ${degree===1?'case':'cases'} grouped around your selection`:'No connected cases under these filters';
$('#clear-selection').hidden=!state.selected;
if(animate&&Object.keys(previous).length&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const start=performance.now();const step=now=>{const t=Math.min(1,(now-start)/420),ease=1-Math.pow(1-t,3);displayPositions=Object.fromEntries(Object.entries(pos).map(([id,p])=>{const from=previous[id]||p;return[id,{id,x:from.x+(p.x-from.x)*ease,y:from.y+(p.y-from.y)*ease}]}));if(t===1)displayPositions=pos;paintPositions();if(t<1)layoutFrame=requestAnimationFrame(step);else layoutFrame=0};layoutFrame=requestAnimationFrame(step);}}
function updateHighlights(){const active=state.hovered||state.selected,neighbors=new Set(state.edges.filter(e=>e.source===active||e.target===active).flatMap(e=>[e.source,e.target]));if(active)neighbors.add(active);$$('#network .node').forEach(n=>{const id=n.dataset.case;n.classList.toggle('dimmed',!!active&&!neighbors.has(id));n.classList.toggle('selected',id===state.selected);n.classList.toggle('hovered',id===state.hovered);n.setAttribute('aria-pressed',String(id===state.selected))});$$('#network .edge').forEach(e=>{const on=e.dataset.source===active||e.dataset.target===active;e.classList.toggle('highlight',on);e.classList.toggle('muted',!!active&&!on)});}
function hidePreview(){clearTimeout(previewTimer);state.hovered=null;$('#node-preview').hidden=true;$$('#network [aria-describedby]').forEach(n=>n.removeAttribute('aria-describedby'));updateHighlights();}
function scheduleHide(){clearTimeout(previewTimer);previewTimer=setTimeout(hidePreview,180);}
function showPreview(node){if(drag||layoutFrame)return;clearTimeout(previewTimer);const c=byId[node.dataset.case];if(!c)return;const es=state.edges.filter(e=>e.source===c.id||e.target===c.id),selectedEdge=state.selected&&state.selected!==c.id?es.find(e=>e.source===state.selected||e.target===state.selected):null;
const related=selectedEdge?[selectedEdge]:es,shared=[...new Set(related.flatMap(e=>Object.values(e.shared).flat()))];
const year=c.fields.year.map(v=>v.value).join(' · '),institution=c.fields.institution.map(v=>v.value).join('\n');
const card=$('#node-preview');card.dataset.category=c.id[0];card.innerHTML=`<div class="preview-meta"><span class="dot ${c.id[0]==='C'?'creative':'participatory'}"></span>${escape(c.category)}</div><h2>${escape(caseTitle(c))}</h2>${year?`<div class="preview-year">${escape(year)}</div>`:''}<p class="preview-description">${escape(c.description||'Description not available.')}</p>${institution?`<div class="preview-institution"><span>Institution</span><p>${escape(institution)}</p></div>`:''}<div class="preview-source"><span>Source</span>${c.fields.citation.length?[...new Set(c.fields.citation.map(v=>v.value))].map(v=>`<p>${escape(v)}</p>`).join(''):'<p>No bibliographic source is listed for this case.</p>'}</div><div class="preview-stats">${c.stages.length?`<div><strong>${c.stages.length}</strong><span>stages</span></div>`:''}<div><strong>${es.length}</strong><span>related cases in view</span></div></div>${shared.length?`<div class="preview-shared"><span>${selectedEdge?'Shared with the selected case':'Shared characteristics'}</span><div class="term-chips">${shared.slice(0,3).map(t=>`<span>${escape(terms[t].label)}</span>`).join('')}${shared.length>3?`<span class="more-terms">+${shared.length-3} more</span>`:''}</div></div>`:'<p class="preview-no-links">No related cases under these filters.</p>'}<div class="preview-footer"><span>Select to read more</span><kbd>↵</kbd></div>`;
card.hidden=false;state.hovered=c.id;$$('#network [aria-describedby]').forEach(n=>n.removeAttribute('aria-describedby'));node.setAttribute('aria-describedby','node-preview');positionPreview(node);updateHighlights();}
function positionPreview(node){const card=$('#node-preview'),r=node.querySelector('.node-core').getBoundingClientRect(),w=card.offsetWidth,h=card.offsetHeight,gap=16,viewportWidth=document.documentElement.clientWidth;let x=r.right+gap;if(x+w>viewportWidth-12)x=r.left-w-gap;x=Math.max(12,Math.min(x,viewportWidth-w-12));let y=r.top-40;y=Math.max(12,Math.min(y,innerHeight-h-12));card.style.left=`${x}px`;card.style.top=`${y}px`;}
function transform(){$('#map-layer')?.setAttribute('transform',`translate(${450+state.panX} ${350+state.panY}) scale(${state.zoom}) translate(-450 -350)`)}
function sourceText(value){return escape(value).replace(/https?:\/\/[^\s<>]+/g,url=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${url}</a>`)}
function fieldEntry(label,entry){if(entry?.value==null)return '';return `<div class="field-block"><span class="field-label">${escape(label)}</span><div class="source-text">${sourceText(entry.value)}</div></div>`}
function fieldGroup(label,entries){if(entries.length<2)return fieldEntry(label,entries[0]);return `<div class="field-block"><span class="field-label">${escape(label)}</span><ul class="field-values">${entries.map(e=>`<li class="source-text">${sourceText(e.value)}</li>`).join('')}</ul></div>`}
function citationBlock(c){const citations=[...new Set(c.fields.citation.map(v=>v.value))];return `<section class="case-source" aria-label="Bibliographic source"><h3>Source</h3>${citations.length?citations.map(v=>`<p class="bibliographic-reference">${sourceText(v)}</p>`).join(''):'<p class="source-text">No bibliographic source is listed for this case.</p>'}</section>`}
// Keep quoted phrases and parenthetical tool descriptions together; wording stays verbatim.
function caseTools(c,dimension){const items=[],seen=new Set();for(const stage of c.stages){const raw=String(stage.fields[dimension]?.value??'');let item='',depth=0,quote='';const add=()=>{const value=item.trim(),key=value.replace(/\s+/g,' ').toLowerCase();if(value&&!seen.has(key)){seen.add(key);items.push(value)}item=''};for(const char of raw){if(quote){item+=char;if(char===quote)quote='';continue}if(char==='“'||char==='"'){quote=char==='“'?'”':'"';item+=char;continue}if(char==='('||char==='[')depth++;if(char===')'||char===']')depth=Math.max(0,depth-1);if(!depth&&[',',';','\n','\r'].includes(char))add();else item+=char}add()}return items;}
function renderInspector(){const c=byId[state.selected];$('#inspector').hidden=!c;$('.workspace').classList.toggle('has-selection',!!c);if(!c){$('#inspector').innerHTML='';return}
const es=state.edges.filter(e=>e.source===c.id||e.target===c.id);
let body='';
if(state.tab==='overview'){body=`<p>${escape(c.description||'Description not available.')}</p>`+citationBlock(c)+Object.entries(c.fields).filter(([f])=>!['name','description','citation'].includes(f)).map(([f,vals])=>fieldGroup(labels[f],vals)).join('');}
if(state.tab==='stages'){body=c.stages.length?c.stages.map((s,i)=>`<details ${i===0?'open':''}><summary>${String(i+1).padStart(2,'0')} &nbsp; ${escape(s.fields.stage.value||'Evaluation stage')}</summary>${Object.entries(s.fields).filter(([f])=>f!=='stage').map(([f,v])=>fieldEntry(labels[f],v)).join('')}</details>`).join(''):'<p class="source-text">Evaluation stages are not listed for this case.</p>';}
if(state.tab==='tools'){body=['methods','practices'].map(d=>{const items=caseTools(c,d);return `<section class="tool-section"><h3>${escape(labels[d])}<span class="tool-count">${items.length}</span></h3>${items.length?`<ul class="tool-list">${items.map(value=>`<li>${escape(value)}</li>`).join('')}</ul>`:`<p class="source-text">${d==='methods'?'Methods and tools':'Design practices'} are not listed for this case.</p>`}</section>`}).join('');}
if(state.tab==='connections'){body=`<p class="source-text">${es.length?`${es.length} related cases with these filters. Select one to explore what they share.`:'No related cases with these filters. Try choosing another characteristic.'}</p>`+es.map(e=>{const other=byId[e.source===c.id?e.target:e.source];return `<button class="connection" data-evidence="${other.id}">${escape(caseTitle(other))}<small>${Object.entries(e.shared).map(([d,ts])=>escape(labels[d])+': '+ts.map(t=>escape(terms[t].label)).join('; ')).join('<br>')}</small></button>`}).join('');if(state.evidence){const e=es.find(e=>e.source===state.evidence||e.target===state.evidence);if(e){body='<div class="evidence"><h4>What these cases share</h4>'+Object.entries(e.shared).map(([d,ts])=>ts.map(t=>`<p class="shared-label"><b>${escape(labels[d])}: ${escape(terms[t].label)}</b></p>`+[c.id,state.evidence].map(id=>`<div class="comparison-excerpt"><h5>${escape(caseTitle(byId[id]))}</h5>${[...new Set(D.observations.filter(o=>o.case_id===id&&o.term_id===t).map(o=>o.raw_value))].map(value=>`<p class="source-text">${escape(value)}</p>`).join('')}</div>`).join('')).join('')).join('')+`<button class="text-button" data-case="${state.evidence}">Read related case →</button></div>`+body;}}}
if(state.tab==='references'){body=citationBlock(c);}
$('#inspector').dataset.category=c.id[0];$('#inspector').innerHTML=`<div class="case-head"><div class="case-meta"><span class="dot ${c.id[0]==='C'?'creative':'participatory'}"></span>${escape(c.category)}<button id="close-case" aria-label="Close case details">×</button></div><h2>${escape(caseTitle(c))}</h2><div class="case-counts">${c.stages.length?`<span>${c.stages.length} stages</span>`:''}<span>${es.length} related cases in view</span></div></div><div class="detail-content"><nav class="detail-tabs" aria-label="Case sections">${[['overview','Overview'],['stages','Stages'],['tools','Tools'],['connections','Related cases'],['references','Source']].map(([t,l])=>`<button data-detail="${t}" aria-pressed="${t===state.tab}" class="${t===state.tab?'active':''}">${l}</button>`).join('')}</nav>${body}</div>`;
}
function selectCase(id){hidePreview();if(!state.selected)savedViewport={zoom:state.zoom,panX:state.panX,panY:state.panY};if(state.selected!==id)focusPositions.clear();state.selected=id;state.zoom=1;state.panX=state.panY=0;state.tab='overview';state.evidence=null;renderInspector();renderGraph(true);if(window.innerWidth>1200&&state.view==='network')$(`#network [data-case="${id}"]`)?.focus({preventScroll:true});$('#inspector').scrollTop=0;if(window.innerWidth<=1200)$('#close-case').focus({preventScroll:true});}
function closeCase(){const id=state.selected;state.selected=null;state.evidence=null;restoreViewport();hidePreview();renderInspector();renderGraph(true);const trigger=state.view==='network'?$(`#network [data-case="${id}"]`):$(`#library [data-case="${id}"]`);if(trigger&&state.view!=='dimensions'){trigger.focus({preventScroll:true});hidePreview()}}
function reset(){restoreViewport();manualPositions.clear();layoutCache.key=null;$('#search').value='';$$('input[name=category]').forEach(x=>x.checked=true);$$('input[name=dimension]').forEach(x=>x.checked=defaults.includes(x.value));$('#term').value='';state.selected=null;state.evidence=null;state.zoom=1;state.panX=state.panY=0;updateTerms();render();}
document.addEventListener('click',e=>{const caseButton=e.target.closest('[data-case]');if(caseButton){selectCase(caseButton.dataset.case);return}const detail=e.target.closest('[data-detail]');if(detail){state.tab=detail.dataset.detail;renderInspector();$(`[data-detail="${state.tab}"]`).focus({preventScroll:true});return}const evidence=e.target.closest('[data-evidence]');if(evidence){state.evidence=evidence.dataset.evidence;renderInspector();$('#inspector').scrollTop=0;return}const view=e.target.closest('[data-view]');if(view){hidePreview();state.view=view.dataset.view;$$('[data-view]').forEach(x=>{x.classList.toggle('active',x===view);x.setAttribute('aria-pressed',String(x===view))});$$('.view').forEach(x=>x.hidden=x.id!==state.view+'-view');return}if(e.target.closest('#close-case'))closeCase();});
$('#network').addEventListener('pointerover',e=>{if(e.pointerType==='touch')return;const node=e.target.closest('.node');if(node&&!node.contains(e.relatedTarget))showPreview(node)});
$('#network').addEventListener('pointerout',e=>{const node=e.target.closest('.node');if(node&&!node.contains(e.relatedTarget))scheduleHide()});
$('#network').addEventListener('focusin',e=>{const node=e.target.closest('.node');if(node)showPreview(node)});
$('#network').addEventListener('focusout',scheduleHide);
$('#node-preview').addEventListener('pointerenter',()=>clearTimeout(previewTimer));$('#node-preview').addEventListener('pointerleave',scheduleHide);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#node-preview').hidden)hidePreview();else if(state.selected)closeCase();else if($('.workspace').classList.contains('filters-open'))$('#filter-toggle').click()}});
window.addEventListener('scroll',e=>{if($('#node-preview').hidden||$('#node-preview').contains(e.target))return;const node=$(`#network [data-case="${state.hovered}"]`);if(!node){hidePreview();return}const r=node.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)hidePreview();else positionPreview(node)},true);window.addEventListener('resize',hidePreview);
$('#filter-toggle').addEventListener('click',()=>{const open=$('.workspace').classList.toggle('filters-open');$('#filter-toggle').setAttribute('aria-expanded',String(open));$('#filter-toggle span').textContent=open?'−':'+';});
$('#network').addEventListener('keydown',e=>{const id=e.target.dataset.case;if(!id||drag)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();selectCase(id);return}const directions={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]},direction=directions[e.key];if(direction&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();hidePreview();cancelAnimationFrame(layoutFrame);layoutFrame=0;const p=displayPositions[id],step=(e.shiftKey?40:12)/state.zoom;moveNode(id,p.x+direction[0]*step,p.y+direction[1]*step)}});
$('#search').addEventListener('input',render);$$('input[name=category],#term').forEach(el=>el.addEventListener('change',render));$$('input[name=dimension]').forEach(el=>el.addEventListener('change',()=>{updateTerms();render()}));$('#reset').onclick=reset;$('#empty-reset').onclick=reset;
function zoom(factor){if(drag)return;hidePreview();state.zoom=Math.max(.5,Math.min(3,state.zoom*factor));transform()}
$('#zoom-in').onclick=()=>zoom(1.2);$('#zoom-out').onclick=()=>zoom(1/1.2);$('#zoom-reset').onclick=()=>{state.zoom=1;state.panX=state.panY=0;transform()};
$('#clear-selection').onclick=closeCase;
$('#layout-reset').onclick=()=>{hidePreview();focusPositions.clear();if(!state.selected)manualPositions.clear();layoutCache.key=null;state.zoom=1;state.panX=state.panY=0;renderGraph()};
$('#network').addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.08:1/1.08)},{passive:false});
function localPoint(element,e){const matrix=element.getScreenCTM();return matrix?new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()):null}
function moveNode(id,x,y){if(!Number.isFinite(x)||!Number.isFinite(y))return;if(state.selected)focusPositions.set(id,{x,y});else{manualPositions.set(id,{x,y});Object.assign(layoutCache.positions[id],{x,y})}Object.assign(displayPositions[id],{x,y});const node=$(`#network [data-case="${id}"]`);if(!node)return;node.setAttribute('transform',`translate(${x},${y})`);const label=node.querySelector('text');if(!label.textContent){const title=caseTitle(byId[id]);label.textContent=title.length>23?title.slice(0,21)+'…':title;label.setAttribute('x','0');label.setAttribute('y','34')}$$('#network .edge').forEach(edge=>{if(edge.dataset.source===id){edge.setAttribute('x1',x);edge.setAttribute('y1',y)}if(edge.dataset.target===id){edge.setAttribute('x2',x);edge.setAttribute('y2',y)}})}
$('#network').addEventListener('pointerdown',e=>{if(drag||!e.isPrimary||e.button!==0)return;const node=e.target.closest('.node'),space=node?$('#map-layer'):$('#network'),point=localPoint(space,e);if(!point)return;suppressClickUntil=0;cancelAnimationFrame(layoutFrame);layoutFrame=0;hidePreview();drag={pointerId:e.pointerId,node,space,start:point,clientX:e.clientX,clientY:e.clientY,origin:node?{...displayPositions[node.dataset.case]}:{x:state.panX,y:state.panY},moved:false,capture:node||$('#network')};drag.capture.setPointerCapture(e.pointerId)});
$('#network').addEventListener('pointermove',e=>{if(!drag||drag.pointerId!==e.pointerId)return;if(!drag.moved&&Math.hypot(e.clientX-drag.clientX,e.clientY-drag.clientY)<5)return;const point=localPoint(drag.space,e);if(!point)return;if(!drag.moved){drag.moved=true;hidePreview();$('#network').classList.add('is-dragging');drag.node?.classList.add('dragging')}e.preventDefault();const x=drag.origin.x+point.x-drag.start.x,y=drag.origin.y+point.y-drag.start.y;if(drag.node)moveNode(drag.node.dataset.case,x,y);else{state.panX=x;state.panY=y;transform()}});
function finishDrag(e){if(!drag||drag.pointerId!==e.pointerId)return;const finished=drag;drag=null;$('#network').classList.remove('is-dragging');finished.node?.classList.remove('dragging');if(finished.moved)suppressClickUntil=performance.now()+500;if(finished.capture.hasPointerCapture(e.pointerId))finished.capture.releasePointerCapture(e.pointerId)}
$('#network').addEventListener('pointerup',finishDrag);$('#network').addEventListener('pointercancel',finishDrag);$('#network').addEventListener('lostpointercapture',finishDrag);
$('#network').addEventListener('click',e=>{if(e.detail>0&&performance.now()<suppressClickUntil){e.preventDefault();e.stopPropagation();suppressClickUntil=0}},true);
updateTerms();render();
})();
